### ISSUE TITLE
code quality

### ISSUE THREAD

**Issue by dhineshwiz** [Vignesh-kvb/Vkay#3]
Few neat picks,
Create separate file for script and include in html file
Rename html file to index.html
Format code neatly using line spacing and tabs,
Few changes in code, check below,

`<script>

function printLog() {

      formData = document.getElementById('firstname').value; /* what is form data , is it required */

      if (document.getElementById('male').checked) {
        var Gender = document.getElementById('male').value; /* initialize gender at one place , use camelCasing format for variable names*/
      }
      if (document.getElementById('female').checked) {
        var Gender = document.getElementById('female').value;
      }
      if (document.getElementById('other').checked) {
        var Gender = document.getElementById('other').value;
      }
      var jsondata = {
        "Firstname": document.getElementById('firstname').value,
        "Lastname": document.getElementById('lastname').value,
        "Age": document.getElementById('age').value,
        "Country": document.getElementById('country').value,
        "Gender": Gender
      };
      console.log(JSON.stringify(jsondata)); 
    }
</script>`

**Comment by Vignesh-kvb** [comment]
1. html and script files are separated.
2. camelCasing is followed.
3. gender initialization is done only once to retrieve the selected field.
4. spacing and tabs are done partially - will be taken care once I start working on notepad++.
